name: Publish Package to npmjs and jsr
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write # Required for OIDC
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
          run-install: true
      - run: vp run check
      - run: vp run test
      - run: vp run build
      - run: vpx jsr publish
      - run: vpx env exec npm publish
